services:
  flask-combined:
    image: elena1204/flask-combined:latest
    container_name: flask-combined-app
    ports:
      - "3000:80"   # Frontend (Nginx)
      - "5001:5001" # Backend (Flask API)
    environment:
      - FLASK_APP=app.py
      - PORT=5001
      - FLASK_DEBUG=False
    restart: unless-stopped

